[tools]
python="3.14.0"
task = "3.433"

[env]
_.python.venv = ".venv"

[tasks."act:ls"]
run = "act --container-architecture linux/amd64 -l"

[tasks."act:run:test-python"]
run = "act --container-architecture linux/amd64 -j test-python"
