repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: ruff
        language: system
        types_or:
          - python
          - pyi
        require_serial: true
      - id: mypy
        name: mypy
        entry: mypy
        language: system
        types_or:
          - python
          - pyi
        require_serial: true
        pass_filenames: false