[tool.poetry]
name = "pycodemetrics"
version = "0.1.0"
description = ""
authors = ["mmocchi"]
readme = "README.md"

packages = [
    { include = "pycodemetrics" },
]

[tool.poetry.dependencies]
python = "^3.12"
click = "^8.1.7"
tablate = "^0.1.12"
pandas = "^2.2.2"
tqdm = "^4.66.4"
pydantic = "^2.8.2"
radon = "^6.0.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
