version: "3"

tasks:
  lint:
    desc: "Run ruff linter"
    cmd: ruff check .

  format:
    desc: "Format code with ruff"
    cmd: ruff format .

  fix:
    desc: "Auto-fix linting issues and format code"
    cmds:
      - ruff check --fix .
      - ruff format .

  mypy:
    desc: "Run mypy type checking"
    cmd: mypy src

  test:
    desc: "Run pytest tests"
    cmd: pytest tests

  test-cov:
    desc: "Run pytest with coverage"
    cmd: pytest tests --cov=src/pycodemetrics --cov-report=term-missing --cov-report=xml

  tox:
    desc: "Run tests on all Python versions with tox"
    cmd: tox

  tox-py312:
    desc: "Run tests on Python 3.12 with tox"
    cmd: tox -e py312

  tox-py313:
    desc: "Run tests on Python 3.13 with tox"
    cmd: tox -e py313

  check:
    desc: "Run all checks (lint, mypy, test)"
    deps:
      - lint
      - mypy
      - test

  dev:
    desc: "Format code and run all checks"
    deps:
      - format
      - check
