# PR作成時のチェックを行うワークフロー
name: CI

on:
  pull_request:
    branches: [ main ]
    types: [opened, reopened, synchronize]
    paths:
      - '**.py'
      - 'pyproject.toml'
      - 'poetry.lock'
      - '.github/workflows/pr-checks.yml'

permissions:
  contents: write
  checks: write
  pull-requests: write
  actions: read

jobs:
  test-python:
    runs-on: ubuntu-latest
    steps:
    # リポジトリをチェックアウト
    - uses: actions/checkout@v4

    # Pythonのセットアップ
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    # 依存関係のインストール
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install
    # Lintの実行
    - name: Run lint
      run: poetry run ruff check .
    # Mypyの実行
    - name: Run mypy
      run: poetry run mypy src
    # テストの実行
    - name: Run tests
      run: |
        set -o pipefail
        poetry run pytest tests/ --cov=src/ --junitxml=pytest.xml --cov-report=term-missing | tee pytest-coverage.txt
    # テストカバレッジをPRコメントとして追加
    - name: Pytest coverage comment
      uses: MishaKav/pytest-coverage-comment@v1.1.52
      with:
        pytest-coverage-path: ./pytest-coverage.txt
        junitxml-path: ./pytest.xml
  actions-timeline:
    needs: [test-python]
    runs-on: ubuntu-latest
    steps:
    - uses: Kesin11/actions-timeline@v2
