name: Create Tag and Test Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'New version number (e.g., 1.0.0)'
        required: true
      allow_tag_override:
        description: 'Allow overwriting existing tag'
        type: boolean
        default: false

permissions:
  contents: write
  actions: write

jobs:
  create-tag-and-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry toml requests

    - name: Update version in pyproject.toml
      id: update-version
      run: |
        python - <<EOF
        import toml
        import os
        import requests

        def get_latest_build_number(version):
            url = f"https://test.pypi.org/pypi/pycodemetrics/{version}/json"
            response = requests.get(url)
            if response.status_code == 200:
                releases = response.json()['releases']
                build_numbers = [int(release.split('.')[-1]) for release in releases if release.startswith(f"{version}+")]
                return max(build_numbers) if build_numbers else 0
            return 0

        with open('pyproject.toml', 'r') as f:
            data = toml.load(f)

        old_version = data['tool']['poetry']['version']
        new_version = '${{ github.event.inputs.version }}'

        if old_version != new_version:
            data['tool']['poetry']['version'] = new_version
            print("Version updated from {} to {}".format(old_version, new_version))
            print("version_changed=true")
        else:
            print("Version unchanged: {}".format(old_version))
            print("version_changed=false")

        # Add build number for TestPyPI
        latest_build = get_latest_build_number(new_version)
        new_build = latest_build + 1
        data['tool']['poetry']['version'] = f"{new_version}+{new_build}"

        with open('pyproject.toml', 'w') as f:
            toml.dump(data, f)

        print(f"version={new_version}+{new_build}")
        EOF

        # Set the outputs for the step
        if grep -q "version_changed=true" <<< "$(python -)"; then
          echo "version_changed=true" >> $GITHUB_OUTPUT
        else
          echo "version_changed=false" >> $GITHUB_OUTPUT
        fi
        echo "version=$(python - | grep '^version=' | cut -d'=' -f2)" >> $GITHUB_OUTPUT

    - name: Commit and push changes
      if: steps.update-version.outputs.version_changed == 'true'
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add pyproject.toml
        git commit -m "Bump version to ${{ steps.update-version.outputs.version }}"
        git push

    - name: Check if tag exists
      id: check-tag
      run: |
        if git rev-parse "v${{ github.event.inputs.version }}" >/dev/null 2>&1; then
          echo "tag_exists=true" >> $GITHUB_OUTPUT
        else
          echo "tag_exists=false" >> $GITHUB_OUTPUT
        fi

    - name: Create new tag
      if: steps.check-tag.outputs.tag_exists == 'false'
      run: |
        git tag v${{ github.event.inputs.version }}
        git push origin v${{ github.event.inputs.version }}

    - name: Override existing tag
      if: steps.check-tag.outputs.tag_exists == 'true' && github.event.inputs.allow_tag_override == 'true'
      run: |
        git tag -f v${{ github.event.inputs.version }}
        git push -f origin v${{ github.event.inputs.version }}

    - name: Fail if tag exists and override not allowed
      if: steps.check-tag.outputs.tag_exists == 'true' && github.event.inputs.allow_tag_override != 'true'
      run: |
        echo "Error: Tag v${{ github.event.inputs.version }} already exists and tag override is not allowed."
        exit 1

    - name: Build package
      run: poetry build

    - name: Upload to TestPyPI
      uses: pypa/gh-action-pypi-publish@v1.8.10
      with:
        user: __token__
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy/

    - name: Create or update release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        if gh release view v${{ github.event.inputs.version }} &>/dev/null; then
          gh release delete v${{ github.event.inputs.version }} --yes
        fi
        gh release create v${{ github.event.inputs.version }} \
          --title "Release v${{ github.event.inputs.version }}" \
          --draft \
          --generate-notes \
          ./dist/*.whl
