name: Publish Python Package

on:
  push:
    tags:
      - 'v*.*.*'
      - 'v*.*.*-rc'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
    - name: Build package
      run: poetry build
    - name: Determine publish target
      id: publish-target
      run: |
        if [[ ${{ github.ref }} == *-rc ]]; then
          echo "::set-output name=is_prerelease::true"
        else
          echo "::set-output name=is_prerelease::false"
        fi
    - name: Publish to TestPyPI
      if: steps.publish-target.outputs.is_prerelease == 'true'
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy/
    - name: Publish to PyPI
      if: steps.publish-target.outputs.is_prerelease == 'false'
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
